/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118389-gc6194b50b1-20250201"
#endif /* AVUTIL_FFVERSION_H */
